### ISSUE TITLE
change the 4K device model

### ISSUE THREAD

**Issue by nidewkk** [SNU-HPCS/QIsim#1]
what need i to do if i want to change it to 300K device model?

**Comment by dongmoon-min** [comment]
Hi. Thank you for your interests in our tool :)
There is a temperature option in cmos_device_model, so what you need to do is just changing target temperature to 300K.

`python3.8 cmos_device_model.py -n 14 -t 300`

For cmos_timing_simulator, 300K_cmos and 4K_cmos options are default, so you can see both results when you run the following script (in our homepage).

`python3.8 cmos_timing_simulator.py -sm FTQC -s 25 -t 50 -m 500 -q 32 -c 2 -r 8 -n 14`

If you share more specific plans for your research, I can give you more detailed instructions.

**Comment by nidewkk** [comment]
thank you for your answer!  I am learning to use your tool and I will ask you again if I have any questions.

**Comment by nidewkk** [comment]
hi，Thank you for your last answer.
I am a student and I am currently trying to use your tool on a 300K CMOS-based QCI.Now I am learning to use your tool.I would like to ask how the data in the /timing_simulator/cmos/wires.csv was obtained.




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "SNU-HPCS/QIsim"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2024年4月11日(星期四) 中午11:57
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [SNU-HPCS/QIsim] change the 4K device model (Issue #1)





 
Hi. Thank you for your interests in our tool :)
 There is an option in cmos_device_model, so what you need to do is just changing target temperature to 300K.
 
python3.8 cmos_device_model.py -n 14 -t 300
 
If you share more specific plans for your research, I can give you more detailed instructions.

**Comment by dongmoon-min** [comment]
Hello again :)
Table 2 in our ISCA'23 paper illustrates how we derive the numbers. Specifically,
- Coaxial cable: We use the static/dynamic power number in "Engineering cryogenic setups for 100-qubit scale superconducting circuit systems" [EPJ'19].
- Microstrip: We use the number of commercial product of DelftCircuit; https://delftcircuits.com/product-overview/cf3/
- Photonic link: We utilize the powers in "Control and readout of a superconducting qubit using a photonic link." [Nature'21] and "A cryogenic electro-optic interconnect for superconducting devices" [Nature Electronics'21].
- Superconducting microstrip: We utilize the powers in "Flexible superconducting Nb transmission lines on thin film polyimide for quantum computing applications." [Superconductor Science and Technology '16]

For some data difficult to find power value (i.e., 4K, 100mK power of photonic link, 100mK power of superconducting microstrip), we project power from the 20mK data by following the ratio of coaxial cables.
